
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: eriton
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  logging:
  level:
    org:
      hibernate:
        type: trace